[
    {
        "POLICY NO": "PEDU000001",
        "POL PROD CODE": "EDU",
        "POL PROD NAME": "Education",
        "SUM ASSURED": 10000000,
        "PREMIUM": 39000,
        "PYMT MODE": "M",
        "POL START DATE": "1/2/2018",
        "POL END DATE": "1/2/2028",
        "POL TERM": 10,
        "POL PREM PAY TERM": 10,
        "POL BASIC PREM RATE": 39000,
        "POL STATUS": "A",
        "POL GENDER": "M",
        "POL ASSR NAME": "Simon",
        "POL ASSR DOB": "",
        "POL ASSR AGE": 30,
        "POL ASSR OCCU": "Software engineer",
        "POL LAST INST DATE": "1/1/2028",
        "POL WOP RATE": 1500,
        "POL WOP PREM": 1500,
        "POL OCB RATE": 11000,
        "POL_OCB PREM": 11000,
        "POL BONUS AMT": 0,
        "POL TOTAL PREM": 51500,
        "POL PAID UP DATE": "",
        "POL LAPSE DATE": "",
        "POL CHARGE": "Policy fee",
        "POL CHARGE AMOUNT": 1000,
        "POL RETN SA": 10000000,
        "POL RI SA": 0,
        "POL RI PREM": 0,
        "POL RETN PREM": 2000,
        "POL RFP CODE": 1001,
        "POL RFP NAME": "abc",
        "POL RFP PERC": 10,
        "POL RFP COMM AMOUNT": 1000,
        "POL NO OF PREMIM PAID": 10,
        "POL BEN1 NAME": "",
        "POL BEN1 TYPE": "",
        "POL BEN1 RELATION": "",
        "POL BEN1 SHARE PERC": "",
        "POL BEN2 NAME": "",
        "POL BEN2 TYPE": "",
        "POL BEN2 RELATION": "",
        "POL BEN2 SHARE PERC": ""
    },
    {
        "POLICY NO": "PEDU000002",
        "POL PROD CODE": "EDU",
        "POL PROD NAME": "Education",
        "SUM ASSURED": 20000000,
        "PREMIUM": 47000,
        "PYMT MODE": "M",
        "POL START DATE": "1/7/2020",
        "POL END DATE": "1/7/2030",
        "POL TERM": 10,
        "POL PREM PAY TERM": 10,
        "POL BASIC PREM RATE": 47000,
        "POL STATUS": "A",
        "POL GENDER": "M",
        "POL ASSR NAME": "Jackson",
        "POL ASSR DOB": "",
        "POL ASSR AGE": 32,
        "POL ASSR OCCU": "Software engineer",
        "POL LAST INST DATE": "1/6/2030",
        "POL WOP RATE": 1500,
        "POL WOP PREM": 1500,
        "POL OCB RATE": 11000,
        "POL_OCB PREM": 11000,
        "POL BONUS AMT": 0,
        "POL TOTAL PREM": 59500,
        "POL PAID UP DATE": "",
        "POL LAPSE DATE": "",
        "POL CHARGE": "Policy fee",
        "POL CHARGE AMOUNT": 1000,
        "POL RETN SA": 20000000,
        "POL RI SA": 0,
        "POL RI PREM": 0,
        "POL RETN PREM": 4000,
        "POL RFP CODE": 1001,
        "POL RFP NAME": "abc",
        "POL RFP PERC": 10,
        "POL RFP COMM AMOUNT": 2000,
        "POL NO OF PREMIM PAID": 11,
        "POL BEN1 NAME": "",
        "POL BEN1 TYPE": "",
        "POL BEN1 RELATION": "",
        "POL BEN1 SHARE PERC": "",
        "POL BEN2 NAME": "",
        "POL BEN2 TYPE": "",
        "POL BEN2 RELATION": "",
        "POL BEN2 SHARE PERC": ""
    },
    {
        "POLICY NO": "PEDU000003",
        "POL PROD CODE": "EDU",
        "POL PROD NAME": "Education",
        "SUM ASSURED": 30000000,
        "PREMIUM": 54000,
        "PYMT MODE": "M",
        "POL START DATE": "1/12/2024",
        "POL END DATE": "1/12/2034",
        "POL TERM": 10,
        "POL PREM PAY TERM": 10,
        "POL BASIC PREM RATE": 54000,
        "POL STATUS": "A",
        "POL GENDER": "M",
        "POL ASSR NAME": "Denis",
        "POL ASSR DOB": "",
        "POL ASSR AGE": 49,
        "POL ASSR OCCU": "Project Manager",
        "POL LAST INST DATE": "1/11/2034",
        "POL WOP RATE": 1500,
        "POL WOP PREM": 1500,
        "POL OCB RATE": 11000,
        "POL_OCB PREM": 11000,
        "POL BONUS AMT": 0,
        "POL TOTAL PREM": 66500,
        "POL PAID UP DATE": "",
        "POL LAPSE DATE": "",
        "POL CHARGE": "Policy fee",
        "POL CHARGE AMOUNT": 1000,
        "POL RETN SA": 30000000,
        "POL RI SA": 0,
        "POL RI PREM": 0,
        "POL RETN PREM": 6000,
        "POL RFP CODE": 1069,
        "POL RFP NAME": "xyz",
        "POL RFP PERC": 10,
        "POL RFP COMM AMOUNT": 3000,
        "POL NO OF PREMIM PAID": 11,
        "POL BEN1 NAME": "",
        "POL BEN1 TYPE": "",
        "POL BEN1 RELATION": "",
        "POL BEN1 SHARE PERC": "",
        "POL BEN2 NAME": "",
        "POL BEN2 TYPE": "",
        "POL BEN2 RELATION": "",
        "POL BEN2 SHARE PERC": ""
    },
    {
        "POLICY NO": "PLPLUS000001",
        "POL PROD CODE": "LPLUS002",
        "POL PROD NAME": "Life plus",
        "SUM ASSURED": 60000000,
        "PREMIUM": 72000,
        "PYMT MODE": "M",
        "POL START DATE": "1/3/2022",
        "POL END DATE": "1/3/2032",
        "POL TERM": 10,
        "POL PREM PAY TERM": 10,
        "POL BASIC PREM RATE": 72000,
        "POL STATUS": "A",
        "POL GENDER": "M",
        "POL ASSR NAME": "John",
        "POL ASSR DOB": "",
        "POL ASSR AGE": 29,
        "POL ASSR OCCU": "Accountant",
        "POL LAST INST DATE": "1/2/2032",
        "POL WOP RATE": 1500,
        "POL WOP PREM": 1500,
        "POL OCB RATE": 11000,
        "POL_OCB PREM": 11000,
        "POL BONUS AMT": 1500,
        "POL TOTAL PREM": 84500,
        "POL PAID UP DATE": "",
        "POL LAPSE DATE": "",
        "POL CHARGE": "Policy fee",
        "POL CHARGE AMOUNT": 1000,
        "POL RETN SA": 60000000,
        "POL RI SA": 0,
        "POL RI PREM": 0,
        "POL RETN PREM": 12000,
        "POL RFP CODE": 1012,
        "POL RFP NAME": "mmm",
        "POL RFP PERC": 10,
        "POL RFP COMM AMOUNT": 4500,
        "POL NO OF PREMIM PAID": 8,
        "POL BEN1 NAME": "",
        "POL BEN1 TYPE": "",
        "POL BEN1 RELATION": "",
        "POL BEN1 SHARE PERC": "",
        "POL BEN2 NAME": "",
        "POL BEN2 TYPE": "",
        "POL BEN2 RELATION": "",
        "POL BEN2 SHARE PERC": ""
    },
    {
        "POLICY NO": "PEDU000004",
        "POL PROD CODE": "LPLAN002",
        "POL PROD NAME": "Education",
        "SUM ASSURED": 30000000,
        "PREMIUM": 54000,
        "PYMT MODE": "M",
        "POL START DATE": "1/12/2024",
        "POL END DATE": "1/12/2034",
        "POL TERM": 10,
        "POL PREM PAY TERM": 10,
        "POL BASIC PREM RATE": 54000,
        "POL STATUS": "A",
        "POL GENDER": "M",
        "POL ASSR NAME": "Denis",
        "POL ASSR DOB": "",
        "POL ASSR AGE": 49,
        "POL ASSR OCCU": "Project Manager",
        "POL LAST INST DATE": "1/11/2034",
        "POL WOP RATE": 1500,
        "POL WOP PREM": 1500,
        "POL OCB RATE": 11000,
        "POL_OCB PREM": 11000,
        "POL BONUS AMT": 0,
        "POL TOTAL PREM": 66500,
        "POL PAID UP DATE": "",
        "POL LAPSE DATE": "",
        "POL CHARGE": "Policy fee",
        "POL CHARGE AMOUNT": 1000,
        "POL RETN SA": 30000000,
        "POL RI SA": 0,
        "POL RI PREM": 0,
        "POL RETN PREM": 6000,
        "POL RFP CODE": 1069,
        "POL RFP NAME": "xyz",
        "POL RFP PERC": 10,
        "POL RFP COMM AMOUNT": 3000,
        "POL NO OF PREMIM PAID": 11,
        "POL BEN1 NAME": "",
        "POL BEN1 TYPE": "",
        "POL BEN1 RELATION": "",
        "POL BEN1 SHARE PERC": "",
        "POL BEN2 NAME": "",
        "POL BEN2 TYPE": "",
        "POL BEN2 RELATION": "",
        "POL BEN2 SHARE PERC": ""
    }
]